site_name: "Cours NSI - Premiere / Terminale"
site_url: https://gdemo-nsi.github.io/cours_nsi/
repo_url: https://github.com/gdemo-nsi/cours_nsi
repo_name: gdemo-nsi/cours_nsi

theme:
  name: material
  language: fr
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/toggle-switch-off-outline
        name: Mode sombre
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/toggle-switch
        name: Mode clair
  features:
    - navigation.tabs
    - navigation.expand
    - toc.integrate
    - content.code.copy

extra_css:
  - stylesheets/extra.css

nav:
  - Accueil: index.md
  - Première:
      - Sommaire: premiere/sommaire.md
      - Thème 1 Représentation des données:
          - Cours: premiere/Theme_1_Representation_des_donnees/cours.md
          - Exercices: premiere/Theme_1_Representation_des_donnees/exercices
      - Thème 2:
          - Sommaire: premiere/Theme_2_Nom_du_theme/sommaire.md
      - Thème 3:
          - Sommaire: premiere/Theme_3_Nom_du_theme/sommaire.md
      - Thème 4:
          - Sommaire: premiere/Theme_4_Nom_du_theme/sommaire.md
      - Thème 5:
          - Sommaire: premiere/Theme_5_Nom_du_theme/sommaire.md
      - Thème 6:
          - Sommaire: premiere/Theme_6_Nom_du_theme/sommaire.md
      - Thème 7:
          - Sommaire: premiere/Theme_7_Nom_du_theme/sommaire.md
      - Thème 8:
          - Sommaire: premiere/Theme_8_Nom_du_theme/sommaire.md
      - Thème 9:
          - Sommaire: premiere/Theme_9_Nom_du_theme/sommaire.md
      - Thème 10:
          - Sommaire: premiere/Theme_10_Nom_du_theme/sommaire.md
  - Terminale:
      - Sommaire: terminale/sommaire.md
      
      - Thème 0 - Révisions python :
        - Sommaire : terminale/Theme_0_Revisions_python/sommaire.md
      - Thème 1:
          - Sommaire: terminale/Theme_1_Nom_du_theme/sommaire.md
      - Thème 2:
          - Sommaire: terminale/Theme_2_Nom_du_theme/sommaire.md
      - Thème 3:
          - Sommaire: terminale/Theme_3_Nom_du_theme/sommaire.md
      - Thème 4:
          - Sommaire: terminale/Theme_4_Nom_du_theme/sommaire.md
      - Thème 5:
          - Sommaire: terminale/Theme_5_Nom_du_theme/sommaire.md
      - Thème 6:
          - Sommaire: terminale/Theme_6_Nom_du_theme/sommaire.md
      - Thème 7 - Algorithmique avancée:
          - Theme 7 - Sommaire: terminale/Theme_7_Algorithmique_avancee/sommaire.md
          - 7.1 Diviser pour régner:
              - Cours: terminale/Theme_7_Algorithmique_avancee/7.1_Diviser_pour_regner/cours.md
              - Exercices: terminale/Theme_7_Algorithmique_avancee/7.1_Diviser_pour_regner/exercices.md
          - 7.2 Programmation dynamique:
              - Cours: terminale/Theme_7_Algorithmique_avancee/7.2_Programmation_dynamique/cours.md
              - Exercices: terminale/Theme_7_Algorithmique_avancee/7.2_Programmation_dynamique/exercices.md
          - 7.3 Recherche textuelle:
              - Cours: terminale/Theme_7_Algorithmique_avancee/7.3_Recherche_textuelle/cours.md
              - Exercices: terminale/Theme_7_Algorithmique_avancee/7.3_Recherche_textuelle/exercices.md
      - Thème 8:
          - Sommaire: terminale/Theme_8_Nom_du_theme/sommaire.md
      - Thème 9:
          - Sommaire: terminale/Theme_9_Nom_du_theme/sommaire.md
    
markdown_extensions:
  - md_in_html  #html in div
  - attr_list    #admonitions ???
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      linenums: true
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true



  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
     
plugins:
  - search
  - mkdocs-jupyter:
      include_source: true

repo_name: gdemo-nsi/cours_nsi