site_name: "Cours NSI - Premiere / Terminale"
site_url: https://gdemo-nsi.github.io/cours_nsi/
repo_url: https://github.com/gdemo-nsi/cours_nsi
repo_name: gdemo-nsi/cours_nsi

theme:
  name: material
  language: fr
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/toggle-switch-off-outline
        name: Mode sombre
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/toggle-switch
        name: Mode clair
  features:
    - navigation.tabs
    - navigation.expand
    - toc.integrate
    - content.code.copy

nav:
  - Accueil: index.md
  - Première: 
      - Sommaire : premiere/sommaire.md
      - Thème 1 Representation des donnees: 
        - Sommaire: premiere_nsi/Theme_1_Représentation_des_donnees/sommaire.md
      - Thème 2: premiere/theme02.md
      - Thème 3: premiere/theme03.md
      - Thème 4: premiere/theme04.md
      - Thème 5: premiere/theme05.md
      - Thème 6: premiere/theme06.md
      - Thème 7: premiere/theme07.md
      - Thème 8: premiere/theme08.md
      - Thème 9: premiere/theme09.md
      - Thème 10: premiere/theme10.md
  - Terminale:
      - Sommaire : terminale/sommaire.md
      - Thème 1: terminale/theme01.md
      - Thème 2: terminale/theme02.md
      - Thème 3: terminale/theme03.md
      - Thème 4: terminale/theme04.md
      - Thème 5: terminale/theme05.md
      - Thème 6: terminale/theme06.md
      - Thème 7: terminale/theme07.md
      - Thème 8 - Algorithmique avancée:
        - Sommaire: terminale/Theme_8_Algorithmique_avancée/sommaire.md
        - 8.1 Diviser pour régner:
          - Cours : terminale/Theme_8_Algorithmique_avancée/8.1 Diviser pour régner/cours.md
          - Exercices : terminale/Theme_8_Algorithmique_avancée/8.1 Diviser pour régner/exercices.md
        - 8.2 Programmation dynamique:
          - Cours : terminale/Theme_8_Algorithmique_avancée/8.2 Programmation dynamique/cours.md
          - Exercices : terminale/Theme_8_Algorithmique_avancée/8.2 Programmation dynamique/exercices.md
        - 8.3 Recherche textuelle:
          - Cours : terminale/Theme_8_Algorithmique_avancée/8.3 Recherche textuelle/cours.md
          - Exercices : terminale/Theme_8_Algorithmique_avancée/8.3 Recherche textuelle/exercices.md

      - Thème 9: terminale/theme09.md

markdown_extensions:
  - attr_list    
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      linenums: true
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true



  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
     
plugins:
  - search
  - mkdocs-jupyter:
      include_source: true


repo_url: https://gdemo-nsi.github.io/cours_nsi/

repo_name: gdemo-nsi/cours_nsi