site_name: "Cours NSI - Premiere / Terminale"
site_url: https://gdemo-nsi.github.io/cours_nsi/
repo_url: https://github.com/gdemo-nsi/cours_nsi
repo_name: gdemo-nsi/cours_nsi

theme:
  name: material
  language: fr
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/toggle-switch-off-outline
        name: Mode sombre
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/toggle-switch
        name: Mode clair
  features:
    - navigation.tabs
    - navigation.expand
    - toc.integrate
    - content.code.copy

nav:
  - Accueil: index.md
  - Première:
      - Thème 1: premiere/theme01.md
      - Thème 2: premiere/theme02.md
      - Thème 3: premiere/theme03.md
      - Thème 4: premiere/theme04.md
      - Thème 5: premiere/theme05.md
      - Thème 6: premiere/theme06.md
      - Thème 7: premiere/theme07.md
      - Thème 8: premiere/theme08.md
      - Thème 9: premiere/theme09.md
      - Thème 10: premiere/theme10.md
  - Terminale:
      - Thème 1: terminale/theme01.md
      - Thème 2: terminale/theme02.md
      - Thème 3: terminale/theme03.md
      - Thème 4: terminale/theme04.md
      - Thème 5: terminale/theme05.md
      - Thème 6: terminale/theme06.md
      - Thème 7: terminale/theme07.md
      - Thème 8: terminale/theme08.md
      - Thème 9: terminale/theme09.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      linenums: true
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true

plugins:
  - search
  - mkdocs-jupyter:
      include_source: true